---
apiVersion: v1
kind: Service
metadata:
  name: homer-dashboard
spec:
  selector:
    app: homer-dashboard
  type: ClusterIP
  ports:
    - name: dashboard
      protocol: TCP
      port: 8080
      targetPort: dashboard
